site_name: DDEV Handbook
nav:
    - Home: index.md
    - Company:
        - Mission Vision Values: company/mission-vision-values.md
        - Expense Policy: company/expense-policy.md
        - Out of Office Policy: company/out-of-office-policy.md
        - PTO Policy: company/pto-policy.md
        - Slack Policy: company/slack-policy.md
    - Engineering:
        - Features Pod: engineering/features-pod.md
        - Ops Pod: engineering/ops-pod.md
        - Development: engineering/development.md
        - Support Rotations: engineering/support-rotations.md
        - Support Services: engineering/support-services.md
        - Playbooks: engineering/playbooks.md
    - Marketing:
        - Marketing Pod: marketing/marketing-pod.md
    - OKRs:
        - 2020 Q3 DDEV-Live: okr/2020-q3-ddev-live.md
    - Product:
        - Product Pod: product/product-pod.md
        - Lifecycle Workflow: product/product-lifecycle-workflow.md
    - Project Management:
        - Pods: project-management/pods.md
        - PM Pod: project-management/pm-pod.md
        - Scrum Process: project-management/scrum.md
        - DoD, DoR, RACI: project-management/dor-dod-raci.md
    - Roadmaps:
        - DDEV-Live: roadmaps/ddev-live.md
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - def_list
    - mdx_truly_sane_lists:
        nested_indent: 2
        truly_sane: true
    - nl2br
plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        locale: en
extra_javascript:
  - 'js/extra.js'
theme:
  name: 'material'
  palette:
    primary: 'light-blue'
