site_name: DDEV Handbook

theme:
  name: 'material'
  palette:
    primary: 'light-blue'

nav:
    - Home: index.md
    - Company:
        - Mission Vision Values: company/mission-vision-values.md
        - Expense Policy: company/expense-policy.md
        - PTO Policy: company/pto-policy.md
    - Pods: pods.md
    - Engineering:
        - Development: engineering/development.md
        - Pods: engineering/pods.md
        - Support Rotations: engineering/support-rotations.md
        - Support Services: engineering/support-services.md
        - Playbooks: engineering/playbooks.md
    - Marketing: marketing.md
    - OKRS: okr/introduction.md
    - Product: product.md
    - Project Management: project.md
    - Roadmaps:
        - DDEV-Live: roadmaps/ddev-live.md

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - def_list
    - mdx_truly_sane_lists:
        nested_indent: 2
        truly_sane: true
    - nl2br

plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        locale: en

extra_javascript:
  - 'js/extra.js'
